# BBTravis CI configuration file
language: python
python: 2.7
env:
  CPU_REQUIREMENTS: "24"
  MEM_REQUIREMENTS: "160000"
  DOCKER_IMAGE: forestscribe/docker-buildworker
  matrix:
  - TARGET=qemux86-64 CPU_REQUIREMENTS=24 MEM_REQUIREMENTS=160000
  - TARGET=raspberrypi2 CPU_REQUIREMENTS=24 MEM_REQUIREMENTS=160000

# Tests running commands
script:
  # make frontend_install_tests takes 17 min, so we only do it post submit
  - title: build gdb
    cmd: |
        bash << EOF
        source ./init.sh $TARGET
        bitbake genivi-dev-platform
        EOF
