# BBTravis CI configuration file
language: yocto
env:
  global:
  - CPU_REQUIREMENTS=24
  - MEM_REQUIREMENTS=16000
  - DOCKER_IMAGE=forestscribe/docker-buildworker
  matrix:
  - TARGET=qemux86-64
  - TARGET=raspberrypi2

# Tests running commands
install:
  - title: populate submodules
    cmd: |
        
script:
  # make frontend_install_tests takes 17 min, so we only do it post submit
  - title: build gdb
    cmd: |
        bash << EOF
        source ./init.sh $TARGET
        bitbake genivi-dev-platform
        EOF
